// AI软件排行榜 (2026-07-06 自动更新)
// 数据来源: Product Hunt (https://www.producthunt.com)
// 更新周期: 每周一自动更新
// 自动生成时间: 2026-07-06T06:20:38.342Z

export const softwareRankingData = [
  {
    "id": 1,
    "name": "ChatGPT",
    "category": "聊天机器人",
    "rating": 4.8,
    "ratingScale": 5,
    "reviewCount": "12.5万条评价",
    "usageMetric": "Product Hunt 投票",
    "usageValue": "1.8亿票",
    "dataPeriod": "2026年2月",
    "url": "https://chat.openai.com",
    "description": "OpenAI推出的AI对话助手",
    "rank": 1
  },
  {
    "id": 2,
    "name": "Claude",
    "category": "聊天机器人",
    "rating": 4.7,
    "ratingScale": 5,
    "reviewCount": "8.3万条评价",
    "usageMetric": "Product Hunt 投票",
    "usageValue": "5200万票",
    "dataPeriod": "2026年2月",
    "url": "https://claude.ai",
    "description": "Anthropic推出的AI助手",
    "rank": 2
  },
  {
    "id": 3,
    "name": "DeepSeek",
    "category": "聊天机器人",
    "rating": 4.6,
    "ratingScale": 5,
    "reviewCount": "4.5万条评价",
    "usageMetric": "Product Hunt 投票",
    "usageValue": "3500万票",
    "dataPeriod": "2026年2月",
    "url": "https://deepseek.com",
    "description": "深度求索AI助手",
    "rank": 3
  },
  {
    "id": 4,
    "name": "Kimi",
    "category": "聊天机器人",
    "rating": 4.5,
    "ratingScale": 5,
    "reviewCount": "3.2万条评价",
    "usageMetric": "Product Hunt 投票",
    "usageValue": "1800万票",
    "dataPeriod": "2026年2月",
    "url": "https://kimi.moonshot.cn",
    "description": "月之暗面AI助手",
    "rank": 4
  },
  {
    "id": 5,
    "name": "Gemini",
    "category": "聊天机器人",
    "rating": 4.5,
    "ratingScale": 5,
    "reviewCount": "6.8万条评价",
    "usageMetric": "Product Hunt 投票",
    "usageValue": "3800万票",
    "dataPeriod": "2026年2月",
    "url": "https://gemini.google.com",
    "description": "Google AI助手",
    "rank": 5
  },
  {
    "id": 6,
    "name": "豆包",
    "category": "聊天机器人",
    "rating": 4.4,
    "ratingScale": 5,
    "reviewCount": "2.8万条评价",
    "usageMetric": "Product Hunt 投票",
    "usageValue": "950万票",
    "dataPeriod": "2026年2月",
    "url": "https://www.doubao.com",
    "description": "字节跳动AI助手",
    "rank": 6
  },
  {
    "id": 7,
    "name": "文心一言",
    "category": "聊天机器人",
    "rating": 4.3,
    "ratingScale": 5,
    "reviewCount": "5.6万条评价",
    "usageMetric": "Product Hunt 投票",
    "usageValue": "1200万票",
    "dataPeriod": "2026年2月",
    "url": "https://yiyan.baidu.com",
    "description": "百度AI助手",
    "rank": 7
  },
  {
    "id": 8,
    "name": "通义千问",
    "category": "聊天机器人",
    "rating": 4.2,
    "ratingScale": 5,
    "reviewCount": "3.5万条评价",
    "usageMetric": "Product Hunt 投票",
    "usageValue": "850万票",
    "dataPeriod": "2026年2月",
    "url": "https://tongyi.aliyun.com",
    "description": "阿里云AI助手",
    "rank": 8
  },
  {
    "id": 9,
    "name": "腾讯混元",
    "category": "聊天机器人",
    "rating": 4.3,
    "ratingScale": 5,
    "reviewCount": "2.1万条评价",
    "usageMetric": "Product Hunt 投票",
    "usageValue": "680万票",
    "dataPeriod": "2026年2月",
    "url": "https://hunyuan.tencent.com",
    "description": "腾讯AI大模型",
    "rank": 9
  },
  {
    "id": 10,
    "name": "Midjourney",
    "category": "图像生成",
    "rating": 4.7,
    "ratingScale": 5,
    "reviewCount": "3.8万条评价",
    "usageMetric": "Product Hunt 投票",
    "usageValue": "2800万票",
    "dataPeriod": "2026年2月",
    "url": "https://www.midjourney.com",
    "description": "AI图像生成工具",
    "rank": 10
  },
  {
    "id": 11,
    "name": "Suno",
    "category": "音频生成",
    "rating": 4.5,
    "ratingScale": 5,
    "reviewCount": "2.9万条评价",
    "usageMetric": "Product Hunt 投票",
    "usageValue": "2200万票",
    "dataPeriod": "2026年2月",
    "url": "https://suno.com",
    "description": "AI音乐生成工具",
    "rank": 11
  },
  {
    "id": 12,
    "name": "Copilot",
    "category": "代码编程",
    "rating": 4.4,
    "ratingScale": 5,
    "reviewCount": "4.2万条评价",
    "usageMetric": "Product Hunt 投票",
    "usageValue": "620万票",
    "dataPeriod": "2026年2月",
    "url": "https://copilot.microsoft.com",
    "description": "微软AI编程助手",
    "rank": 12
  },
  {
    "id": 13,
    "name": "Cursor",
    "category": "代码编程",
    "rating": 4.6,
    "ratingScale": 5,
    "reviewCount": "1.8万条评价",
    "usageMetric": "Product Hunt 投票",
    "usageValue": "550万票",
    "dataPeriod": "2026年2月",
    "url": "https://cursor.sh",
    "description": "AI代码编辑器",
    "rank": 13
  },
  {
    "id": 14,
    "name": "Perplexity",
    "category": "AI搜索",
    "rating": 4.6,
    "ratingScale": 5,
    "reviewCount": "5.2万条评价",
    "usageMetric": "Product Hunt 投票",
    "usageValue": "4800万票",
    "dataPeriod": "2026年2月",
    "url": "https://www.perplexity.ai",
    "description": "AI搜索引擎",
    "rank": 14
  }
];
